name: CI-Windows

on:
  push:
    branches: [ '*' ]
    paths-ignore:         # Don't trigger on files that are updated by the CI
      - README.md
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: polze_env
          python-version: 3.9
          auto-activate-base: false
          miniconda-version: "latest"
          auto-update-conda: true
          add-pip-as-python-dependency: true
      - name: Install
        shell: bash -l {0}
        run: |
            python -m pip install -e .
      - name: Test
        shell: bash -l {0}
        run: |
            python -m polze.test

